- name: Create kubernetes repo
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  become: yes
  become_user: root

- name: Disable selinux
  selinux:
    state: disabled
  become: yes
  become_user: root
  when: False

- name: Ensure a list of packages are installed
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
    validate_certs: False
    disable_gpg_check: True
    lock_timeout: 180
  vars:
    packages:
    - kubelet
    - kubeadm
  become: yes
  become_user: root

- name: Start kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root

# LINT-ERROR
- name: Execute kubeadm reset
  command: kubeadm reset -f
  become: yes
  become_user: root

- name: Execute kubeadm reset
  command: swapoff -a
  become: yes
  become_user: root