

- name: "Helm List"
  command: /usr/local/bin/helm list
  become: yes
  become_user: root
  register: helm_list
  changed_when: False

- name: "Deploy external-dns"
  command: "/usr/local/bin/helm install --name external-dns stable/external-dns --set provider=aws --set aws.zoneType=public --set txtOwnerId={{hosted_zone}} --set domainFilters[0]={{domaine}} --set rbac.create=true --set logLevel=debug"
  become: yes
  become_user: root
  when: "'external-dns' not in helm_list.stdout"