helm install stable/external-dns --set aws.credentials.accessKey=acces_key
  --set aws.credentials.secretKey=secret_key --set provider=aws --set aws.zoneType=public --set txtOwnerId=Z26RPPVUP5NQWM --set domainFilters[0]=melkouhen.net