- name: "Create folder /etc/docker"
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  become: yes
  become_user: root

- name: "Create Folder docker.service.d"
  file:
    path: /etc/systemd/system/docker.service.d
    mode: 0755
    state: directory
  become: yes
  become_user: root

# LINT-ERROR
- name: "Add Docker Repo"
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes
  become_user: root

- name: Install container-selinux
  yum:
    name: http://vault.centos.org/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
    state: present
    update_cache: True
    validate_certs: false
    lock_timeout: 180
  become: yes
  become_user: root
  ignore_errors: True
  when: "'tag_Name_Master' in groups"

- name: "Ensure a list of packages installed"
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
    validate_certs: false
#    lock_timeout: 180
  vars:
    packages:
      - docker-ce
      - device-mapper-persistent-data
      - lvm2
  become: yes
  become_user: root

- name: "Create Groupe Docker"
  group:
    name: docker
    state: present
  become: yes
  become_user: root

- name: "Configure Daemon.json"
  template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json
  become: yes
  become_user: root
  when: registry is defined

- name: "Configure Docker Service"
  template:
    src: templates/etc_sysconfig_docker
    dest: /etc/sysconfig/docker
  become: yes
  become_user: root
  when: registry is defined

- name: "Install logrotate"
  yum:
    name: logrotate
    state: present
#    lock_timeout: 180

- name: "Copy logrotate conf file"
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/docker
  become: true

- name: "Start Docker Service"
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root
