- name: "Compute Public IP"
  set_fact:
    public_ip: "{{groups['tag_Name_Node'][0] | map('extract', hostvars,  'ipv4') }}"
  when:
    - public_ip is not defined
    - "'tag_Name_Node' in groups"

- debug:
    msg: "{{public_ip}}"

- fail: