apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    # The ACME server URL
    server: {{acme}}
    # Email address used for ACME registration
    email: mehdi.elkouhen@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-issuer
    # Enable the HTTP-01 challenge provider
    #http01: {}

    dns01:
      providers:
        - name: dns
          route53:
            region: us-east-1
            accessKeyID: AKIAZFKTAHHP2YGYM5WR
            secretAccessKeySecretRef:
              name: acme-route53
              key: secret-access-key